buildscript {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$androidGradlePluginVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        classpath "com.mobidevelop.robovm:robovm-gradle-plugin:$roboVMVersion"
    }
}

allprojects {
    version = "1.0"

    repositories {
        mavenCentral()
        google()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}

configure(subprojects.findAll { it.name != "android" }) {
    apply plugin: "org.jetbrains.kotlin.jvm"
}
